Fix dependencies and tests
thecodingmachine/schema-analyzer pull request #13
Opened 2024-01-27 21:40 UTC by aszenz

Follow up of https://github.com/thecodingmachine/schema-analyzer/commit/0ccb1a2a5d1b4434ea613178778d6ecb7be53cdf

To support dbal v3 fully i bumped up the dependencies and php versions

Also added github ci and removed travis

2024-01-27 21:42 UTC, aszenz commented
@nguyenk This pr should make releasing v2 possible

2024-01-29 10:57 UTC, aszenz commented
@moufmouf This one is similar to other prs:
- https://github.com/thecodingmachine/dbal-fluid-schema-builder/pull/12
- https://github.com/thecodingmachine/tdbm-fluid-schema-builder/pull/22

2024-01-31 21:51 UTC, homersimpsons commented on tests/SchemaAnalyzerTest.php
> +        $this->expectException(SchemaAnalyzerTableNotFoundException::class, "Could not find table 'rights'. Did you mean 'right'?");
I may be wrong, but `"Could not find table 'rights'. Did you mean 'right'?"` should be in an `expectExceptionMessage`, no ?

```suggestion
        $this->expectException(SchemaAnalyzerTableNotFoundException::class);
        $this->expectExceptionMessage("Could not find table 'rights'. Did you mean 'right'?");
```

2024-01-31 21:52 UTC, homersimpsons requested changes
Thank you for your work on this ! Just a small concern about a test and then it is ready to merge.

2024-02-01 09:25 UTC, aszenz commented
> Thank you for your work on this ! Just a small concern about a test and then it is ready to merge.

Applied the suggestion, the assertion message is different than expectedException message indeed

2024-02-01 11:52 UTC, merged

2024-02-01 11:54 UTC, homersimpsons commented
Thank you for your contribution !

I saw you had some open Pull Request targeting your own forks. Maybe those are not ready yet, or the target is not correct:

- https://github.com/aszenz/magic-query/pull/1
- https://github.com/aszenz/schema-version-control/pull/1

2024-02-01 12:36 UTC, aszenz commented
> Thank you for your contribution !
> 
> I saw you had some open Pull Request targeting your own forks. Maybe those are not ready yet, or the target is not correct:
> 
>     * [Use v2 of schema-analyzer aszenz/magic-query#1](https://github.com/aszenz/magic-query/pull/1)
> 
>     * [Update dbal to v3 aszenz/schema-version-control#1](https://github.com/aszenz/schema-version-control/pull/1)

Those were for testing the ci pipeline, now they can be closed

2024-02-01 12:38 UTC, aszenz commented
Can u do a release of v2 as well, or something else needs merging

2024-02-01 19:28 UTC, homersimpsons commented
> Can u do a release of v2 as well, or something else needs merging

I did a pre-release:
- https://github.com/thecodingmachine/schema-analyzer/releases/tag/v2.0.0-beta.2
- https://packagist.org/packages/mouf/schema-analyzer#v2.0.0-beta.2

If it is stable, I can do a real release. I do not think we have to merge anything else.